# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/html_truncator/all/html_truncator.rbi
#
# html_truncator-0.4.2

class HTML_Truncator
  def self.ellipsable_tags; end
  def self.ellipsable_tags=(arg0); end
  def self.punctuation_chars; end
  def self.punctuation_chars=(arg0); end
  def self.self_closing_tags; end
  def self.self_closing_tags=(arg0); end
  def self.truncate(text, max, opts = nil); end
end
class Nokogiri::HTML::DocumentFragment < Nokogiri::XML::DocumentFragment
  def ellipsable?; end
end
class Nokogiri::XML::Node
  def ellipsable?; end
  def inner_truncate(max, opts); end
  def self_closing?; end
  def truncate(max, opts); end
end
class Nokogiri::XML::Text < Nokogiri::XML::CharacterData
  def truncate(max, opts); end
end
