#!/usr/bin/env ruby

require "pry_wrench"

command = ARGV.count > 0 ? ARGV[0].chomp.strip : ''

if command == "help" || command == "--help" || command == "-h"
  puts PryWrench.help
  return
end

puts PryWrench.main
