AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Style/Documentation:
  Enabled: false