[tools]
jq = "1"
node = "24"

[tasks.install]
alias = "i"
description = "Install dependencies"
run = "npm install"

[tasks.'ts:extract']
description = "Extract artworks with the TypeScript implementation"
run = "npm -s run extract"

[tasks.test]
description = "Run tests"
run = [
    "npm run test",
    "echo 'Comparing solution with expected output...'",
    """
    diff \\
      <(mise run ts:extract './files/van-gogh-paintings.html' | jq --sort-keys) \\
      <(cat ./files/expected-array.json | jq --sort-keys)
    """,
    "echo 'Tests completed successfully'"
]
