source 'https://rubygems.org'

ruby '2.6.5'

gem 'nokogiri', '~> 1.10.7'
gem 'watir', '~> 6.16.5'

group :test, :development do
  gem 'pry', '~> 0.12.2'
end

group :test do
  gem 'rspec', '~> 3.9.0'
end
