/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package serpapicodechallenge;

import static org.junit.Assert.*;

import static java.util.stream.Collectors.joining;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.junit.Test;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Optional;

public class AppTest {

    private static final String NAME_1 = "The Starry Night";
    private static final String LINK_1 = buildAbsoluteLink("/search?q=The+Starry+Night");
    private static final String EXTENSION_1 = "1889";
    private static final String IMAGE_ID_1 = "image_1";
    private static final String IMAGE_SRC_1 = buildImageSrc("abcd");

    private static final String NAME_2 = "Sunflowers";
    private static final String LINK_2 = buildAbsoluteLink("/search?q=Sunflowers");
    private static final String IMAGE_ID_2 = "image_2";
    private static final String IMAGE_SRC_2 = buildImageSrc("efgh");

    private static final String NAME_3 = "The Potato Eaters";
    private static final String LINK_3 = buildAbsoluteLink("/search?q=The+Potato+Eaters");
    private static final String EXTENSION_3 = "3885";
    private static final String IMAGE_ID_3 = "image_3";
    private static final String IMAGE_SRC_3 = buildImageSrc("ijkl");

    @Test
    public void parseCarousel_zeroItems_succeeds() throws IOException {
        ObjectMapper objectMapper = new ObjectMapper();
        String htmlString = buildHtmlString(new String[0], new String[0]);

        JsonNode artworksJson = App.parseCarousel(
                objectMapper,
                new ByteArrayInputStream(htmlString.getBytes()));

        JsonNode expected = objectMapper.readTree(buildJsonString());
        assertEquals(expected, artworksJson);
    }

    @Test
    public void parseCarousel_oneItem_succeeds() throws IOException {
        ObjectMapper objectMapper = new ObjectMapper();
        String htmlString = buildHtmlString(
                new String[]{
                        buildSingleCarouselItem(
                                NAME_1,
                                LINK_1,
                                IMAGE_ID_1,
                                Optional.of(EXTENSION_1))
                }, new String[]{
                        buildSingleImageIdJS(IMAGE_ID_1, IMAGE_SRC_1)
                });

        JsonNode artworksJson = App.parseCarousel(
                objectMapper,
                new ByteArrayInputStream(htmlString.getBytes()));

        JsonNode expected = objectMapper.readTree(
                buildJsonString(
                        buildSingleJsonItem(NAME_1, LINK_1, Optional.of(IMAGE_SRC_1), Optional.of(EXTENSION_1)))
        );
        assertEquals(expected, artworksJson);
    }

    @Test
    public void parseCarousel_multipleItems_succeeds() throws IOException {
        ObjectMapper objectMapper = new ObjectMapper();
        String htmlString = buildHtmlString(
                new String[]{
                        buildSingleCarouselItem(
                                NAME_1,
                                LINK_1,
                                IMAGE_ID_1,
                                Optional.of(EXTENSION_1)),
                        buildSingleCarouselItem(
                                NAME_2,
                                LINK_2,
                                IMAGE_ID_2,
                                Optional.empty()),
                        buildSingleCarouselItem(
                                NAME_3,
                                LINK_3,
                                IMAGE_ID_3,
                                Optional.of(EXTENSION_3))
                }, new String[]{
                        buildSingleImageIdJS(IMAGE_ID_1, IMAGE_SRC_1),
                        buildSingleImageIdJS(IMAGE_ID_2, IMAGE_SRC_2),
                        buildSingleImageIdJS(IMAGE_ID_3, IMAGE_SRC_3)
                });

        JsonNode artworksJson = App.parseCarousel(
                objectMapper,
                new ByteArrayInputStream(htmlString.getBytes()));

        JsonNode expected = objectMapper.readTree(
                buildJsonString(
                        buildSingleJsonItem(NAME_1, LINK_1, Optional.of(IMAGE_SRC_1), Optional.of(EXTENSION_1)),
                        buildSingleJsonItem(NAME_2, LINK_2, Optional.of(IMAGE_SRC_2), Optional.empty()),
                        buildSingleJsonItem(NAME_3, LINK_3, Optional.of(IMAGE_SRC_3), Optional.of(EXTENSION_3)))
        );
        assertEquals(expected, artworksJson);
    }

    @Test
    public void parseCarousel_withoutExtension_succeeds() throws IOException {
        ObjectMapper objectMapper = new ObjectMapper();
        String htmlString = buildHtmlString(
                new String[]{
                        buildSingleCarouselItem(
                                NAME_2,
                                LINK_2,
                                IMAGE_ID_2,
                                Optional.empty())
                }, new String[]{
                        buildSingleImageIdJS(IMAGE_ID_2, IMAGE_SRC_2)
                });

        JsonNode artworksJson = App.parseCarousel(
                objectMapper,
                new ByteArrayInputStream(htmlString.getBytes()));

        JsonNode expected = objectMapper.readTree(
                buildJsonString(
                        buildSingleJsonItem(NAME_2, LINK_2, Optional.of(IMAGE_SRC_2), Optional.empty()))
        );
        assertEquals(expected, artworksJson);
    }

    @Test
    public void parseCarousel_withoutImageSrc_succeeds() throws IOException {
        ObjectMapper objectMapper = new ObjectMapper();
        String htmlString = buildHtmlString(
                new String[]{
                        buildSingleCarouselItem(
                                NAME_3,
                                LINK_3,
                                IMAGE_ID_3,
                                Optional.of(EXTENSION_3))
                }, new String[0]);

        JsonNode artworksJson = App.parseCarousel(
                objectMapper,
                new ByteArrayInputStream(htmlString.getBytes()));

        JsonNode expected = objectMapper.readTree(
                buildJsonString(
                        buildSingleJsonItem(NAME_3, LINK_3, Optional.empty(), Optional.of(EXTENSION_3)))
        );
        assertEquals(expected, artworksJson);
    }

    @Test
    public void parseCarousel_malformedPage_throws() throws IOException {
        ObjectMapper objectMapper = new ObjectMapper();
        String htmlString = "<html>" +
                "<head></head>" +
                "<body>" +
                "<div>" +
                "<span>There is no scrolling carousel</span>" +
                "</div>" +
                "</body>" +
                "</html>";

        assertThrows(
                NoSuchElementException.class,
                () -> App.parseCarousel(
                        objectMapper,
                        new ByteArrayInputStream(htmlString.getBytes())));
    }

    @Test
    public void parseImageIdsToSrcs_zeroIds_succeeds() {
        Document document = Jsoup.parse(buildHtmlString(new String[0], new String[0]));

        Map<String, String> imageIdsToSrcs = App.parseImageIdsToSrcs(document);

        assertTrue(imageIdsToSrcs.isEmpty());
    }

    @Test
    public void parseImageIdsToSrcs_oneId_succeeds() {
        Document document = Jsoup.parse(buildHtmlString(
                new String[0],
                new String[]{buildSingleImageIdJS(IMAGE_ID_1, IMAGE_SRC_1)}
        ));

        Map<String, String> imageIdsToSrcs = App.parseImageIdsToSrcs(document);

        assertEquals(1, imageIdsToSrcs.size());
        assertTrue(imageIdsToSrcs.containsKey(IMAGE_ID_1));
        assertEquals(IMAGE_SRC_1, imageIdsToSrcs.get(IMAGE_ID_1));
    }

    @Test
    public void parseImageIdsToSrcs_multipleIds_succeeds() {
        Document document = Jsoup.parse(buildHtmlString(
                new String[0],
                new String[]{
                        buildSingleImageIdJS(IMAGE_ID_1, IMAGE_SRC_1),
                        buildSingleImageIdJS(IMAGE_ID_2, IMAGE_SRC_2),
                        buildSingleImageIdJS(IMAGE_ID_3, IMAGE_SRC_3)}
        ));

        Map<String, String> imageIdsToSrcs = App.parseImageIdsToSrcs(document);

        assertEquals(3, imageIdsToSrcs.size());
        assertTrue(imageIdsToSrcs.containsKey(IMAGE_ID_1));
        assertEquals(IMAGE_SRC_1, imageIdsToSrcs.get(IMAGE_ID_1));
        assertTrue(imageIdsToSrcs.containsKey(IMAGE_ID_2));
        assertEquals(IMAGE_SRC_2, imageIdsToSrcs.get(IMAGE_ID_2));
        assertTrue(imageIdsToSrcs.containsKey(IMAGE_ID_3));
        assertEquals(IMAGE_SRC_3, imageIdsToSrcs.get(IMAGE_ID_3));
    }

    @Test
    public void parseImageIdsToSrcs_malformedIds_throws() {
        Document document = Jsoup.parse(
                "<html><head></head><body>" +
                        "<script>function _setImagesDifferently(e,c){var x='hi';}()</script>" +
                        "</body></html>");

        assertThrows(NoSuchElementException.class, () -> App.parseImageIdsToSrcs(document));
    }

    private static String buildHtmlString(String[] imageCarouselLines, String[] imageIdJSLines) {
        String imageCarousel = Arrays.stream(imageCarouselLines).collect(joining());
        String imageIdJS = Arrays.stream(imageIdJSLines).collect(joining());
        return "<!doctype html>" +
                "<html>" +
                "<head></head>" +
                "<body>" +
                "<g-scrolling-carousel><div><div>" +
                imageCarousel +
                "</div></div></g-scrolling-carousel>" +
                "<script>function _setImagesSrc(e,c){function f(a){a.onerror=function(){" +
                "a.style.display=\"none\"};a.src=c}for(var g=0,b=void 0;b=e[g++];){var " +
                "d=document.getElementById(b);d?f(d):(google.iir=google.iir||{},google." +
                "iir[b]=c)}};" +
                imageIdJS +
                "</script>" +
                "</body>" +
                "</html>";
    }

    /*
     * Builds a carousel item, of the form:
     * <div>
     *   <a aria-label="The Starry Night" href="/search?q=The+Starry+Night">
     *     <div>
     *       <div>
     *         <div>
     *           <g-img>
     *             <img id="kximg0">
     *           </g-img>
     *         </div>
     *       </div>
     *     </div>
     *     <div>
     *       <div></div>
     *       (This child only present if the subtitle is provided)
     *       <div>1889</div>
     *     </div>
     *   </a>
     * </div>
     * for the given aria label, href, image ID, and (optional) subtitle.
     */
    private static String buildSingleCarouselItem(
            String ariaLabel,
            String href,
            String imageId,
            Optional<String> subtitle) {
        String result =
                "<div><a aria-label=\"" +
                        ariaLabel +
                        "\" href=\"" +
                        href +
                        "\"><div><div><div><g-img><img id=\"" +
                        imageId +
                        "\"></g-img></div></div></div><div><div></div>";
        if (subtitle.isPresent()) {
            result += "<div>" + subtitle.get() + "</div>";
        }

        result += "</div></a></div>";
        return result;
    }

    /*
     * Builds a line of JS of the form:
     *   (function(){var s='data:image/jpeg;base64,/9j\x3d';var ii=['im0'];_setImagesSrc(ii,s);})();
     * for the given image ID (e.g. 'im0') and image source (e.g. 'data:image/jpeg;base64,/9j\x3d').
     */
    private static String buildSingleImageIdJS(String imageId, String imageSrc) {
        return
                "(function(){var s='" +
                        imageSrc +
                        "';var ii=['" +
                        imageId +
                        "'];_setImagesSrc(ii,s);})();";
    }

    private static String buildImageSrc(String base64Data) {
        return "data:image/jpeg;base64" + base64Data;
    }

    private static String buildAbsoluteLink(String relativeLink) {
        return "https://www.google.com" + relativeLink;
    }

    private static String buildJsonString(String... jsonItems) {
        String mergedJsonItems = Arrays.stream(jsonItems).collect(joining(","));
        return "{\"artworks\": [" + mergedJsonItems + "]}";
    }

    /*
     * Builds a string of JSON of the form:
     *   {
     *     "name":"The Starry Night",
     *     "link":"https://www.google.com/search?q=The+Starry+Night",
     *     "image":"data:image/jpeg;base64abcd",
     *     "extensions":["1889"]
     *   }
     *
     * The imageSrc is optional; if it is omitted, "image" is mapped to null.
     *
     * The extension is optional; if it is omitted, the "extensions" key is
     * omitted from the JSON object entirely.
     */
    private static String buildSingleJsonItem(
            String name,
            String link,
            Optional<String> imageSrc,
            Optional<String> extension) {
        String result =
                "{\"name\": \"" + name + "\"," +
                        "\"link\": \"" + link + "\"," +
                        "\"image\": ";
        if (imageSrc.isPresent()) {
            result += "\"" + imageSrc.get() + "\"";
        } else {
            result += "null";
        }
        if (extension.isPresent()) {
            result += ",\"extensions\": [\"" + extension.get() + "\"]";
        }
        return result + "}";
    }
}
