module Parsers
  class GoogleImage < Base
    # These class names seem to be generated by some Google algorithm and might be easily re-generated causing our Parser to fail.
    IMAGE_SLIDER_CLASS = 'MiPcId'
    IMAGE_NAME_CLASS = 'kltat'
    IMAGE_EXTENSIONS_CLASS = 'ellip'
    IMAGE_LINK_CLASS = 'klitem'

    GOOGLE_BASE_URL = 'https://www.google.com'

    def initialize(file_path:)
      super
    end

    def call
      paintings_slider_elements_html = document.search(".appbar .#{IMAGE_SLIDER_CLASS}")
      images_script = document.css('script').find { |script| script.text.include?('setImagesSrc') && script.text.include?('data:image') }

      images = paintings_slider_elements_html.map { |image_html| as_image_record(image_html:, images_script:) }
                                             .map(&:to_h)

      { artworks: images }
    end

    private

    def as_image_record(image_html:, images_script:)
      image = Image.new

      Image::ATTRIBUTES.each do |attribute|
        image.send("#{attribute}=", send(attribute, image_html: , images_script:))
      end

      image
    end

    def extensions(**args)
      extensions_text = args[:image_html].search("div.#{IMAGE_EXTENSIONS_CLASS}").first

      [extensions_text.content.strip] if extensions_text
    end

    def image(**args)
      image_node = args[:image_html].search('img').first
      return unless image_node

      image_id = image_node.get_attribute('id')
      return unless image_id

      match = args[:images_script].content.match(/s='([\S]*)';var ii=\['#{image_id}'\]/)

      match[1].gsub('\\', '') if match # I couldn't figure out why I need to escape '/' character in order to make my link result look like the one in the expected-array.json
    end

    def link(**args)
      link_node = args[:image_html].search("a.#{IMAGE_LINK_CLASS}").first
      "#{GOOGLE_BASE_URL}#{link_node.get_attribute('href')}" if link_node
    end

    def name(**args)
      name_text = args[:image_html].search("div.#{IMAGE_NAME_CLASS}").first
      name_text.content.strip if name_text
    end
  end
end