# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "pry", "~> 0.14.1"

gem "rspec", "~> 3.10"

gem "json", "~> 2.5"
gem "nokogiri", "~> 1.12"
