name: Rubocop

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Set up rubocop-rspec
        run: gem install rubocop-rspec
      - name: Rubocop Linter Action
        uses: andrewmcodes/rubocop-linter-action@v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
