source "https://rubygems.org"

# Specify your gem's dependencies in carousel_parser.gemspec
gemspec

gem "rake", "~> 12.0"
gem "rspec", "~> 3.0"

gem "nokogiri", "~> 1.10"

gem "addressable", "~> 2.7"
